# Generated by Django 5.1.6 on 2025-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='role',
            field=models.CharField(choices=[('TALENT', 'Talent'), ('CASTING', 'Casting Professional'), ('ADMIN', 'Admin')], default='TALENT', max_length=10),
        ),
    ]
