# Generated by Django 5.1.6 on 2025-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPerView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
